project_lists/urls.py
from django.urls import path
from project_lists.views.PDF import Pdf
from project_lists.views.help import Help
from project_lists.views.use_case import CUView
from project_lists.views.use_case_add import CUAdd
from . import views
from .views import (DashBoardView, DashBoardAdd, ProjectUpdate, ProjectDelete,
                    ComponentUpdate, ComponentDelete, ComponentsView, ComponentAdd,
                    EstimationOptionsView, MTVEstimate, MTVDetailsView,
                    MTVMDetailsView, MTVMEstimate, RePCUDetailsView, RePCUEstimate, editMTV, editMTVM,
                    MTVDetailsEditView, MTVMDetailsEditView, TechFactorsAdd, EnvFactorsAdd, ActorsAdd, AddUC,
                    UseCaseDelete, AverageView, DuplicateView, duplicateAllData, editProject)

app_name = "project_lists"
urlpatterns = [

    # ABM DE PROYECTOS y estimacion
    path('dashboard/list_update/<int:pk>/', ProjectUpdate.as_view(), name='update_list'),
    path('dashboard/list_update/<int:pk>/project/edit', views.editProject, name='test'),
    path('dashboard/list_delete/<int:pk>/', ProjectDelete.as_view(), name='delete_list'),
    path('dashboard/<int:pk>/dashboard_add/', DashBoardAdd.as_view(), name='dashboard_add'),
    path('dashboard/project_delete/<int:pk>/', ProjectDelete.as_view(), name='dashboard_delete'),
    path('dashboard/', DashBoardView.as_view(), name='dashboard'),
    path('estimate/<int:project>/', EstimationOptionsView.as_view(), name='estimate'),
    path('dashboard/<int:pk>/<int:mod>/average_estimate/', AverageView.as_view(), name='average_estimate'),
    path('dashboard/<int:pk>/duplicate/', DuplicateView.as_view(), name='duplicate'),
    path('dashboard/<int:pk>/duplicate/duplicateAllData/', views.duplicateAllData, name='duplicateAllData'),


    # ABM DE COMPONENTES
    path('edit_project_components/<int:project>/<int:pk>/edit', ComponentUpdate.as_view(), name='components_edit'),
    path('edit_project_components/<int:pk>/add', ComponentAdd.as_view(), name='add_components'),
    path('edit_project_components/<int:project>/<int:pk>/delete', ComponentDelete.as_view(), name='component_delete'),
    path('edit_project_components/<int:pk>/components/', ComponentsView.as_view(), name='edit_project_components'),


    # METODOS DE ESTIMACION

    # MTV
    path('mtv/<int:pk>/mtv/editMTV/', views.editMTV, name='mtv_edit'),
    path('mtv/<int:pk>/view/', MTVDetailsView.as_view(), name='mtv_details'),
    path('mtv/<int:pk>/edit', MTVDetailsEditView.as_view(), name='mtv_details_edit'),
    path('mtv/<int:pk>/estimate', MTVEstimate.as_view(), name='mtv_estimate'),

    # MTV_M
    path('mtv_m/<int:pk>/mtvm/editMTVM/', views.editMTVM, name='mtvm_edit'),
    path('mtv_m/<int:pk>/view/', MTVMDetailsView.as_view(), name='mtvm_details'),
    path('mtv_m/<int:pk>/edit', MTVMDetailsEditView.as_view(), name='mtvm_details_edit'),
    path('mtv_m/<int:pk>/estimate', MTVMEstimate.as_view(), name='mtvm_estimate'),

    # REPCU
    path('repcu/<int:pk>/', RePCUDetailsView.as_view(), name='repcu_details'),
    path('repcu/<int:pk>/estimate', RePCUEstimate.as_view(), name='repcu_estimate'),

    # REPCU - FACT. TECNICOS
    path('repcu/<int:pk>/techfactors/', TechFactorsAdd.as_view(), name='techfactors'),
    path('repcu/<int:pk>/techfactors/editTF/', views.editTechFactors, name='techfactors_edit'),

    # REPCU - FACT. AMBIENTALES
    path('repcu/<int:pk>/envfactors/editEF/', views.editEnvFactors, name='envfactors_edit'),
    path('repcu/<int:pk>/envfactors/', EnvFactorsAdd.as_view(), name='envfactors'),

    # REPCU - ACTORES
    path('repcu/<int:pk>/actors/', ActorsAdd.as_view(), name='actors'),
    path('repcu/<int:pk>/actors/editAC/', views.editActors, name='actors_edit'),

    # REPCU - CASO DE USO
    path('repcu/<int:pk>/cuadd/', CUAdd.as_view(), name='use_case_add'),
    path('repcu/<int:pk>/cu/', CUView.as_view(), name='cu'),
    path('repcu/<int:pk>/cuadd/repcu/ucAdd', views.AddUC, name='add'),
    path('repcu/<int:comp>/<int:pk>/ucDel/', UseCaseDelete.as_view(), name='use_case_del'),
    path('repcu/<int:comp>/<int:pk>/ucDel/delete/', views.del_uc, name='use_case_delete_function'),


    # DOWNLOAD
    path('pdf/<int:met>/<int:pk>', Pdf.as_view(), name='pdf_MTV'),
    path('pdf/<int:met>/<int:pk>', Pdf.as_view(), name='pdf_MTVM'),
    path('pdf/<int:met>/<int:pk>', Pdf.as_view(), name='pdf_PCU'),

    path('help/', Help.as_view(), name='help'),

]

src/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import landing_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_view, name="home_page"),
    path('', include('accounts.urls')),
    path('', include('project_lists.urls'))
]

project_lists/views/MTVM_details.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render_to_response
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView
from django.views.generic.edit import DeleteView, FormMixin, FormView
from project_lists.forms import ComponentForm
from project_lists.models import Component, ProjectList
from django.shortcuts import redirect


# Create your views here.
class MTVMDetailsView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Component
    template_name = "project_lists/mtvm_details_view.html"
    success_url = reverse_lazy('project_lists:mtvm_details_view')
    success_message = "bla."
    fields = '__all__'

    def get_success_url(self):
        project = self.kwargs.get('pk')
        return reverse('project_lists:mtvm_details_view', kwargs={'pk': project})

    def get_context_data(self, **kwargs):
        context = super(MTVMDetailsView, self).get_context_data(**kwargs)
        project_id = self.kwargs.get('pk')
        context['project'] = ProjectList.objects.filter(id=project_id).first()
        components = Component.objects.filter(list_id=self.kwargs.get('pk'))
        context['components'] = components
        context['project_name'] = ProjectList.objects.get(id=project_id).name
        time = ProjectList.objects.get(id=project_id).time
        if time is 1:
            context['project_time'] = "Días"
        if time is 2:
            context['project_time'] = "Horas"
        if time is 3:
            context['project_time'] = "Minutos"
        return context

    def render_to_response(self, context, **response_kwargs):
        context['component'] = Component.objects.filter(list=self.kwargs.get('pk'))
        context['object'] = ProjectList.objects.filter(id=self.kwargs.get('pk')).first()
        return super(MTVMDetailsView, self).render_to_response(context, **response_kwargs)


class MTVMDetailsEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Component
    template_name = "project_lists/mtvm_details_edit.html"
    success_url = reverse_lazy('project_lists:mtvm_details_edit')
    # success_message = ""
    fields = '__all__'

    def get_success_url(self):
        project = self.kwargs.get('pk')
        return reverse('project_lists:mtvm_details_edit', kwargs={'pk': project})

    def get_context_data(self, **kwargs):
        context = super(MTVMDetailsEditView, self).get_context_data(**kwargs)
        project_id = self.kwargs.get('pk')
        context['project'] = ProjectList.objects.filter(id=project_id).first()
        components = Component.objects.filter(list_id=self.kwargs.get('pk'))
        context['components'] = components
        context['project_name'] = ProjectList.objects.get(id=project_id).name
        time = ProjectList.objects.get(id=project_id).time
        if time is 1:
            context['project_time'] = "Días"
        if time is 2:
            context['project_time'] = "Horas"
        if time is 3:
            context['project_time'] = "Minutos"
        return context

    def render_to_response(self, context, **response_kwargs):
        context['component'] = Component.objects.filter(list=self.kwargs.get('pk'))
        context['object'] = ProjectList.objects.filter(id=self.kwargs.get('pk')).first()
        return super(MTVMDetailsEditView, self).render_to_response(context, **response_kwargs)


def editMTVM(request, **kwargs):
    components_id = request.POST.getlist("id")
    components_optimist = request.POST.getlist("optimist")
    components_pessimist = request.POST.getlist("pessimist")
    components_average = request.POST.getlist("average")
    components_risk = request.POST.getlist("risk")
    project_id = kwargs.get('pk')
    for c in components_id:
        optimist_value = components_optimist.pop(0)
        pessimist_value = components_pessimist.pop(0)
        average_value = components_average.pop(0)
        risk_value = components_risk.pop(0)
        component = Component.objects.get(id=c)
        component.optimist = optimist_value
        component.pessimist = pessimist_value
        component.average = average_value
        component.riskValue = risk_value
        component.save()
    url = "/mtv_m/" + str(project_id) + "/estimate"
    return redirect(url)

project_lists/views/MTV_details.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render_to_response
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView
# from django.views.generic.edit import DeleteView, FormMixin, FormView
from project_lists.models import Component, ProjectList
from django.shortcuts import redirect

# Create your views here.

from django.http import HttpResponseRedirect
from django.shortcuts import render


class MTVDetailsView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Component
    template_name = "project_lists/mtv_details_view.html"
    success_url = reverse_lazy('project_lists:mtv_details_view')
    success_message = "Exito!."
    fields = '__all__'

    def get_success_url(self):
        project = self.kwargs.get('pk')
        return reverse('project_lists:mtv_details_view', kwargs={'pk': project})

    def get_context_data(self, **kwargs):
        context = super(MTVDetailsView, self).get_context_data(**kwargs)
        project_id = self.kwargs.get('pk')
        context['project'] = ProjectList.objects.filter(id=project_id).first()
        components = Component.objects.filter(list_id=self.kwargs.get('pk'))
        context['components'] = components
        context['project_name'] = ProjectList.objects.get(id=project_id).name
        time = ProjectList.objects.get(id=project_id).time
        if time is 1:
            context['project_time'] = "Días"
        if time is 2:
            context['project_time'] = "Horas"
        if time is 3:
            context['project_time'] = "Minutos"
        return context

    def render_to_response(self, context, **response_kwargs):
        context['component'] = Component.objects.filter(list=self.kwargs.get('pk'))
        context['object'] = ProjectList.objects.filter(id=self.kwargs.get('pk')).first()
        return super(MTVDetailsView, self).render_to_response(context, **response_kwargs)


class MTVDetailsEditView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Component
    template_name = "project_lists/mtv_details_edit.html"
    success_url = reverse_lazy('project_lists:mtv_details_edit')
    # success_message = ""
    fields = '__all__'

    def get_success_url(self):
        project = self.kwargs.get('pk')
        return reverse('project_lists:mtv_details_edit', kwargs={'pk': project})

    def get_context_data(self, **kwargs):
        context = super(MTVDetailsEditView, self).get_context_data(**kwargs)
        project_id = self.kwargs.get('pk')
        context['project'] = ProjectList.objects.filter(id=project_id).first()
        components = Component.objects.filter(list_id=self.kwargs.get('pk'))
        context['components'] = components
        context['project_name'] = ProjectList.objects.get(id=project_id).name
        time = ProjectList.objects.get(id=project_id).time
        if time is 1:
            context['project_time'] = "Días"
        if time is 2:
            context['project_time'] = "Horas"
        if time is 3:
            context['project_time'] = "Minutos"
        return context

    def render_to_response(self, context, **response_kwargs):
        context['component'] = Component.objects.filter(list=self.kwargs.get('pk'))
        context['object'] = ProjectList.objects.filter(id=self.kwargs.get('pk')).first()
        return super(MTVDetailsEditView, self).render_to_response(context, **response_kwargs)


def editMTV(request, **kwargs):
    components_id = request.POST.getlist("id")
    components_optimist = request.POST.getlist("optimist")
    components_pessimist = request.POST.getlist("pessimist")
    components_average = request.POST.getlist("average")
    project_id = kwargs.get('pk')
    for c in components_id:
        optimist_value = components_optimist.pop(0)
        pessimist_value = components_pessimist.pop(0)
        average_value = components_average.pop(0)
        component = Component.objects.get(id=c)
        component.optimist = optimist_value
        component.pessimist = pessimist_value
        component.average = average_value
        component.save()

    url = "/mtv/" + str(project_id) + "/estimate"
    return redirect(url)

project_lists/views/PDF.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import View, CreateView
from django.utils import timezone
from project_lists.models import *
from .render import Render
from decimal import *


class Pdf(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "project_lists/PDF.html"
    model = Component
    fields = '__all__'

    def get(self, request, **kwargs):
        project_id = self.kwargs.get('pk')
        today = today = timezone.now()
        metodo = self.kwargs.get('met')
        components = Component.objects.filter(list_id=self.kwargs.get('pk'))
        estimate_mtv = ProjectList.objects.get(id=self.kwargs.get('pk')).estimate_mtv
        estimate_mtvm = ProjectList.objects.get(id=self.kwargs.get('pk')).estimate_mtvm
        estimate_pcu = ProjectList.objects.get(id=self.kwargs.get('pk')).estimate_pcu
        tot_envFactors = 0
        tot_techFact = 0
        if EnvFactors.objects.filter(idProject=project_id).exists():
            envFactors = EnvFactors.objects.get(idProject=self.kwargs.get('pk'))
            tot_envFactors = (
                    (envFactors.familiarityWithTheProject * Decimal('1.5')) + (
                    envFactors.applicationExperience * Decimal('0.5')) +
                    envFactors.objectOrientedProgrammingExperience +
                    + (envFactors.leadAnalystCapability * Decimal('0.5')) + envFactors.motivation + (
                            envFactors.stableRequirements * 2)
                    - envFactors.partTimeStaff - envFactors.difficultProgrammingLanguage)
            tot_envFactors = Decimal('1.4') - (Decimal('0.03') * Decimal(tot_envFactors))
        if TechFactors.objects.filter(idProject=project_id).exists():
            techFactors = TechFactors.objects.get(idProject=self.kwargs.get('pk'))
            tot_techFact = (
                                   (techFactors.distributedSystem * 2) + techFactors.complexInternalProcessing
                                   + (techFactors.crossPlatformSupport * 2) + techFactors.customSecurity
                                   + techFactors.dependenceThirdPartyCode + (techFactors.easyToChange / 2) +
                                   techFactors.endUserEfficency + techFactors.highlyConcurrent + techFactors.installationEasiness
                                   + techFactors.responseTime + techFactors.reusableCode +
                                   (techFactors.usability / 2) + techFactors.userTraining) / 100
            tot_techFact = tot_techFact + Decimal('0.6')
        tot_PCU = 0
        for component in components:
            tot_PCU = tot_PCU + component.weightCU + component.actorsAmount
        project_name = ProjectList.objects.get(id=self.kwargs.get('pk')).name
        params = {
            'components': components,
            'project': project_name,
            'today': today,
            'estimate_mtv': estimate_mtv,
            'estimate_mtvm': estimate_mtvm,
            'estimate_pcu': estimate_pcu,
            'tot_envFactors': tot_envFactors,
            'tot_techFact': tot_techFact,
            'tot_PCU': tot_PCU,
            'metodo': metodo,
            'request': request
        }
        return Render.render('project_lists/PDF.html', params)

project_lists/templates/project_lists/dashboard.html
{% extends 'project_lists/base.html' %}
{% block title %}
    Inicio
{% endblock %}
{% block content %}

    <div class="modal modal-dialog modal-login modal-clear alien-modal-form" id="FormModal"
         tabindex="-1" role="dialog" style="color: black">
    </div>

    <div class="row" style="margin-top:-20px">
        <div class="col-md-8 ml-auto mr-auto">
            <div class="card card-plain" style="color:black">
                <div class="card-body bg-white" style="opacity:.65">
                    

                    {% for message in messages %}
                        <div class="alert {{ message.tags }} " >
                            <button type="button" class="close" >
                          
                             </button>
                             {{ message }}
                        </div>
                      {% endfor %}

                    <div class="pull-left">
                            <a href="{% url 'project_lists:dashboard_add' owner.id %}"
                                class="padding-five btn btn-primary btn-round float-right">
                                <i class="material-icons padding-five"> + </i>
                            </a>
                    </div>
                    
                    <div class="table-responsive ">
                       <table class="table table-hover table-fixed">
                            {% if project_lists %}
                                <thead class="">
                                <tr>
                                    <th>
                                        Proyectos
                                    </th>
                                    <th>
                                        Creado el...
                                    </th>
                                    <th class="text-center">
                                        Actualizado el...
                                    </th>
                                    <th class="text-right">
                                         Acciones
                                    </th>
                                </tr>
                                </thead>

                                <tbody>
                                    {% for list in project_lists %}
                                        <tr>
                                            <td>
                                                {{ list.name }}
                                            </td>
                                            <td class="text-center">
                                                {{ list.date_created }}
                                            </td>
                                            <td class="text-center">
                                                {{ list.date_updated }}
                                            </td>
                                            <td class="text-right">
                                                <a align="left" class="nav-link" href="{% url 'project_lists:update_list' list.id %}">Modificar</a>
                                                <a align="left" class="nav-link" href="{% url 'project_lists:edit_project_components' list.id %}">Componentes</a>
                                                <a align="left"  class="nav-link" href="{% url 'project_lists:dashboard_delete' list.id %}">Eliminar</a>
                                                <a align="left" class="nav-link" href="{% url 'project_lists:pdf_MTV' '4' list.id %}">Descargar</a>

                                            </td>
                                            <td class="text-right">
                                                <a  align="left" class="nav-link" href="{% url 'project_lists:duplicate' list.id %}">Duplicar</a>
                                                <a  align="left" class="nav-link" href="{% url 'project_lists:estimate' list.id %}">Estimar</a>
                                                <a  align="left" class="nav-link" href="{% url 'project_lists:average_estimate' list.id 0 %}">Consultar Estimaciones</a>
                                                <a  align="left" class="nav-link" href="{% url 'project_lists:average_estimate' list.id 1 %}">Estimación Avanzada</a>

                                            </td>
                                        
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            {% else %}
                                
                                <thead>
                                    <h6>
                                        TODAVÍA NO HAS AGREGADO PROYECTOS, POR FAVOR CREA UNO UTILIZANDO EL BOTÓN DE + 
                                    </h6>
                                </thead>
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project_lists/templates/project_lists/edit_project_components_add.html
{% extends 'project_lists/base.html' %}
{% block title %}
    Agregar Componente
{% endblock %}
{% block content %}
       <div class="modal-dialog" role="">
            <div class="modal-content">
                <div class="modal-header d-block">
                <div class="d-flex">
                    <h4 class="modal-title" style="color:black">Agregar componente al proyecto: {{ project_name }}  </h4>

                    <button type="button" class="close" onClick="javascript:history.go(-1);">
                            <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
                <div class="modal-body">
                    <div class="card-body">
                      <form class="form" method="POST"
                                 action="{% url 'project_lists:edit_project_components'  project_id %}">
                               {% csrf_token %}
                               <span>
                                    <div class="input-group form-group-no-border input-lg">
                                        {{ form.name }}
                                    </div>
                                    <input class="input-group form-group-no-border input-lg" style="display:none" name="list" value={{project_id}} />
                                     <button type="submit" class="btn btn-primary btn-round btn-lg btn-block"> Agregar </button>
                                </span>
                           </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary"onClick="javascript:history.go(-1);">Volver</button> -->
                 </div>
            </div>
        </div>


{% endblock %}

project_lists/templates/project_lists/repcu_details.html
{% extends 'project_lists/base.html' %}
{% block title %}
    RePCU para {{ object.name }}
{% endblock %}
{% block content %}

    <div class="row" style="margin-top:-20px">
        <div class="col-md-8 ml-auto mr-auto">
              
                <a href="{% url 'project_lists:dashboard' %}"
                class="btn btn-neutral pull-left">❮ Volver al inicio</a>

                <div class="text-center"  >
                    <a href="{% url 'project_lists:repcu_estimate' project.id  %}"
                    class="btn btn-neutral float-left" style="color:white; background:#3498DB;font-size: 12px">
                    <strong>Estimar</strong></a>
                    <a href="{% url 'project_lists:techfactors' project.id   %}"
                    class="btn btn-neutral float-left" style="color:white; background:#3498DB ;font-size: 12px">
                    Factores Técnicos</a>
                     <a href="{% url 'project_lists:envfactors' project.id   %}"
                     class="btn btn-neutral float-left" style="color:white; background:#3498DB ;font-size:12px">
                    Factores Ambientales</a>
                 
                 
                 <a href="{% url 'project_lists:pdf_MTV' '3' project.id %}"
                    class="btn btn-neutral float-right" style="color:white; background:#3498DB ;font-size: 12px">
                    <span class="glyphicon glyphicon-download-alt"></span>  Descargar
                </a>
                <a href="{% url 'project_lists:edit_project_components' project.id  %}"
                    class="btn btn-neutral float-right " style="color:white; background:#3498DB ;font-size: 12px">Editar Componentes</i>
                 </a>
              </div>
                       
                <div class="card card-plain" style="color:black">
                    <div class="card-body bg-white" style="opacity: .65">
                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            <div class="container">
                                <div class="alert-icon">
                                    <i class="now-ui-icons objects_support-17"></i>
                                </div>
                                <strong>Oh no!</strong>
                                {% for error in form.errors %}
                                    {{ form.errors.as_text | escape }}
                                {% endfor %}
                                <button type="button" class="close" data-dismiss="alert"
                                        aria-label="Close">
						<span aria-hidden="true">
							<i class="now-ui-icons ui-1_simple-remove"></i>
						</span>
                                </button>
                            </div>
                        </div>
                    {% endif %}
                   
                    {% if messages %}
                        <div class="alert alert-success" role="alert">
                            <div class="container">
                                <div class="alert-icon">
                                    <i class="now-ui-icons ui-2_like"></i>
                                </div>
                                <strong>Bien!</strong>
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                                <button type="button" class="close" data-dismiss="alert"
                                        aria-label="Close">
  						<span aria-hidden="true">
							<i class="now-ui-icons ui-1_simple-remove"></i>
						</span>
                                </button>
                            </div>
                        </div>
                    {% endif %}

                     <div class="pull-left">
                    <h5 class="modal-title" style="color:grey;font-size: medium;" align="left">Proyecto: {{ project_name }} </h5>
                         <h1 class="modal-title" style="color:grey;font-size: small;" align="left">Unidad de tiempo: {{ project_time}} </h1>
                    <div class="text-right " >

                    </div>

                     

                    </div>

                    <div class="table-responsive " >
                        <table class="table">
                            {% if components %}
                                <thead class="">
                                <tr>
                                    <th>
                                       Componente
                                    </th>
                                    <th>
                                       Peso CU
                                    </th>
                                    <th>
                                       Peso Actores
                                    </th>
                                     <th>
                                       Acciones
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for item in components %}
                                    <tr>
                                        <td>
                                            {{ item.name }}
                                        </td>
                                        <td>
                                            {{ item.weightCU }}
                                        </td>
                                         <td>
                                            {{ item.actorsAmount }}
                                        </td>
                                       <td class="text-right"> 
                                             <a  align="center" class="nav-link" href="{% url 'project_lists:actors' item.id %}">Actores</a>
                                             <a  align="center" class="nav-link" href="{% url 'project_lists:cu' item.id %}">Casos de Uso</a>
                                             <a  align="center" class="nav-link" href="{% url 'project_lists:component_delete' project.id item.id %}">Eliminar</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            {% else %}
                                <br>
                                <br>
                                <thead>
                                <tr>
                                    <h6>
                                        TODAVÍA NO HAS AGREGADO COMPONENTES, POR FAVOR CREA UNO UTILIZANDO EL BOTÓN DE + 
                                    </h6>
                                </tr>
                                </thead>
                            {% endif %}
                        </table>
                    </div>
                </div>

            </div>
    </div>
{% endblock %}