accounts/urls.py
from django.urls import path

from .views import (ConfirmResetPassword, CustomPasswordResetCompleteView,
                    DoneResetPassword, LoginView, ResetPassword, SignUpView, CustomLogoutView)

app_name = "accounts"
urlpatterns = [
    path('signup/', SignUpView.as_view(), name="signup"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', CustomLogoutView.as_view(), name="logout"),
    path('reset/', ResetPassword.as_view(), name="reset"),
    path('reset_done/', DoneResetPassword.as_view(), name="reset_done"),
    path('reset/<uidb64>/<token>/', ConfirmResetPassword.as_view(), name="reset_confirm"),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='reset_complete'),
]

src/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import landing_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_view, name="home_page"),
    path('', include('accounts.urls')),
    path('', include('project_lists.urls'))
]

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


class UserManager(BaseUserManager):
    """Custom manager for our custom user."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        """Creates a regular/ non-admin user"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """ Creates a super user"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """Custom user model."""
    username = None
    email = models.EmailField(_("email address"), unique=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

accounts/forms.py
"""Forms for our shopping list."""
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm, PasswordResetForm,
                                       SetPasswordForm)
from django.contrib.auth import password_validation
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import User


class CustomPasswordResetForm(PasswordResetForm):
    """Extension to current auth password reset form"""
    email = forms.EmailField(
        max_length=50,
        widget=forms.EmailInput(attrs={
            "class": "form-control",
            "placeholder": "Your Email...",
        })

    )
    use_https = True


class CustomAuthenticationForm(AuthenticationForm):
    """Modified form from auth"""
    reset_password = CustomPasswordResetForm
    username = forms.EmailField(
        max_length=50,
        widget=forms.EmailInput(attrs={
            "class": "form-control",
            "placeholder": "Email",
            "autocomplete": "email",
            "autofocus": True,
        })

    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Password",
                "autocomplete": "password",
            }
        )
    )


class CustomUserCreationForm(UserCreationForm):
    """Modified signup form"""

    email = forms.EmailField(
        max_length=50,
        widget=forms.EmailInput(attrs={
            "class": "form-control",
            "placeholder": "Your Email...",
            "autocomplete": "email",
            "autofocus": True,
        })

    )
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Password",
                "autocomplete": "password",
            }
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Password Confirm",
                "autocomplete": "password",
            }
        ),
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = ("email",)


class CustomSetPasswordForm(SetPasswordForm):
    """Customised set password form for css magic.."""
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "New Password",
                "autocomplete": "none",
            }
        ),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "New password confirmation",
                "autocomplete": "password",
            }
        )
    )

accounts/views.py
from django.contrib.auth.views import (LoginView, PasswordResetView, PasswordResetConfirmView,
                                       PasswordResetDoneView, PasswordResetCompleteView, LogoutView)
from django.views.generic import CreateView

from .forms import CustomAuthenticationForm, CustomUserCreationForm, CustomSetPasswordForm
from django.urls import reverse_lazy

# Create your views here.


class LoginView(LoginView):
    """Form view for Login"""
    form_class = CustomAuthenticationForm
    template_name = "accounts/login-page.html"
    redirect_authenticated_user = True

class SignUpView(CreateView):
    """Creating a new non-super-user"""
    template_name = "accounts/sign-up-page.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("accounts:login")


class ResetPassword(PasswordResetView):
    """Sends email to user for password reset."""
    email_template_name = 'accounts/emails/password_reset_email.html'
    success_url = reverse_lazy('accounts:reset_done')


class DoneResetPassword(PasswordResetDoneView):
    """Tells user that email for reset has been send reset done."""
    template_name = 'accounts/reset_done.html'


class ConfirmResetPassword(PasswordResetConfirmView):
    """Returns form for changing the password."""
    form_class = CustomSetPasswordForm
    success_url = reverse_lazy('accounts:reset_complete')
    template_name = 'accounts/reset_confirm.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    """Notifies User thank password change has been completed successfully"""
    template_name = 'accounts/reset_complete.html'


class CustomLogoutView(LogoutView):
    """Cutomised logout view"""
    next_page = reverse_lazy("home_page")


accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="gr__demos_creative-tim_com">
<head>
    <meta charset="utf-8">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "main/img/apple-icon.png" %}">
    <link rel="icon" type="image/png" href="{% static "main/img/favicon.png" %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block title %}{% endblock %} </title>

    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no"
          name="viewport">

    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

    <!-- CSS Files -->
    <link href="{% static "accounts/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "accounts/css/now-ui-kit.css" %}" rel="stylesheet">

</head>

<body class="signup-page" data-gr-c-s-loaded="true">
<nav class="navbar navbar-expand-lg bg-white navbar-absolute navbar-transparent">
    <div class="container">


        <div class="navbar-translate">
            <a class="navbar-brand" href="/" rel="tooltip"
               data-placement="bottom">
                Home
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navigation" aria-controls="navigation-index" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
        </div>
    </div>

</nav>

<div class="page-header section-image">
    <div class="page-header-small"
         style="background-color:whitesmoke" ;></div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>


    <footer class="footer " style="background-color: black;">


            <div class="container">
                <div class="copyright" style="color: white; float: left;">
                    © 2019, Developed by <a href="" target="_blank">Vittoria Melloni</a>
                    & <a href="" target="_blank"> Jessica Llorente</a>
                </div>
                <div class="copyright" style="color: white; float: right;">
                         Mentored by <a href="" target="_blank">Pablo Ortiz Bochard</a>
                </div>
            </div>
        
        
        </footer>

</div>


<!--   Core JS Files   -->
<script src="{% static "main/js/core/jquery.3.2.1.min.js" %}" type="text/javascript"></script>
<script src="{% static "main/js/core/popper.min.js" %}" type="text/javascript"></script>
<script src="{% static "main/js/core/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "accounts/js/plugins/moment.min.js" %}"></script>

<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static "main/js/plugins/bootstrap-switch.js" %}"></script>

<!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
<script src="{% static "accounts/js/plugins/bootstrap-tagsinput.js" %}"></script>

<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="{% static "accounts/js/plugins/bootstrap-selectpicker.js" %}"
        type="text/javascript"></script>

<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{% static "accounts/js/plugins/jasny-bootstrap.min.js" %}"></script>

<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static "main/js/plugins/nouislider.min.js" %}" type="text/javascript"></script>

<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="{% static "accounts/js/plugins/bootstrap-datetimepicker.min.js" %}"
        type="text/javascript"></script>

<!-- Plugins for Presentation Page -->
<!-- Sharrre Library -->
<script src="
{% static "main/js/plugins/jquery.sharrre.js" %}" type="text/javascript"></script>

<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="{% static "accounts/js/now-ui-kit.js" %}" type="text/javascript"></script>


<div style="display: none;"></div>
<div id="shadowMeasureIt"></div>
<div id="divCoordMeasureIt"></div>
<div id="divRectangleMeasureIt">
    <div id="divRectangleBGMeasureIt">
    </div>
</div>
</body>
</html>

accounts/templates/accounts/login-page.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="gr__demos_creative-tim_com">
<head>
    <meta charset="utf-8">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'main/img/apple-icon.png' %}">
    <style></style>
    <link rel="icon" type="image/png" href="{% static 'main/img/favicon.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Login Page </title>

    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no"
          name="viewport">
    <!-- CSS Files -->
    <link href="{% static 'accounts/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'accounts/css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'accounts/css/now-ui-kit.css' %}" rel="stylesheet">
</head>

<body class="login-page" data-gr-c-s-loaded="true">
<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-white fixed-top navbar-transparent" color-on-scroll="500">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand"
               href="{% url 'home_page' %}" rel="tooltip"
               title="" data-placement="bottom">
                Home
            </a>
        </div>

        <div class="collapse navbar-collapse has-image" data-color="orange">
        </div>
    </div>
</nav>
<!-- End Navbar -->
<div class="page-header section-image" filter-color="orange" style="background-color: rgba(0,0,0,0)">
    <div class="page-header-image"
         style="background-image:url({% static 'main/img/login.jpg' %})" ;>
    </div>
    <div class="content">
        <div class="modal modal-dialog modal-login modal-primary" id="ResetPassModal" tabindex="-1"
             role="dialog"
             aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5     class="modal-title" id="exampleModalLabel">Reset Password</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card-body">
                            <form class="form" method="POST" action="{% url 'accounts:reset' %}">
                                {% csrf_token %}
                                <div class="input-group form-group-no-border input-lg">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i
                                            class="now-ui-icons ui-1_email-85"></i></span>
                                    </div>
                                    {{ form.reset_password.email }}
                                </div>
                                <input type="hidden" name="next" value="{% url 'admin:index' %}">
                                <div class="card-footer text-center">
                                    <button type="submit"
                                            class="btn btn-neutral btn-round btn-lg btn-block">
                                        Reset Password
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-5 ml-auto mr-auto" style="margin-top:150px">
                    <div class="card card-login card-plain">
                        <div class="card-body">
                            {% if form.errors %}
                                <div class="alert alert-danger" role="alert">
                                    <strong>Oh snap!</strong>
                                    {% for error in form.errors %}
                                        {{ form.errors.as_text | escape }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                            <form class="form" method="POST" action="{% url 'accounts:login' %}">
                                {% csrf_token %}
                                <div class="input-group form-group-no-border input-lg">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i
                                            class="now-ui-icons ui-1_email-85"></i></span>
                                    </div>
                                    {{ form.username }}
                                </div>
                                <div class="input-group form-group-no-border input-lg">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i
                                            class="now-ui-icons ui-1_lock-circle-open"></i></span>
                                    </div>
                                    {{ form.password }}
                                </div>
                                <div class="card-footer text-center">
                                    <button type="submit"
                                            class="btn btn-primary btn-round btn-lg btn-block">Ingresar
                                    </button>
                                </div>
                            </form>
                        </div>
                        <div class="pull-left">
                            <h6><a href="{% url 'accounts:signup' %}" class="link footer-link">
                                Crear Cuenta</a></h6>
                        </div>
                        <div class="pull-right">
                            <h6><a href="#" data-toggle="modal"
                                   data-target="#ResetPassModal" class="link footer-link">Olvidaste tu contraseña?</a></h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="footer " style="background-color: black;">


    <div class="container">
        <div class="copyright" style="color: white; float: left;">
            © 2019, Developed by <a href="" target="_blank">Vittoria Melloni</a>
            & <a href="" target="_blank"> Jessica Llorente</a>
        </div>
        <div class="copyright" style="color: white; float: right;">
                 Mentored by <a href=""
                                       target="_blank">Pablo Ortiz Bochard</a>
            </div>
    </div>


</footer>

<!-- </div> -->


<!--   Core JS Files   -->
<script src="{% static 'main/js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'main/js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'accounts/js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'accounts/js/plugins/moment.min.js' %}"></script>

<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'main/js/plugins/bootstrap-switch.js' %}"></script>

<!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
<script src="{% static 'accounts/js/plugins/bootstrap-tagsinput.js' %}"></script>

<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="{% static 'accounts/js/plugins/bootstrap-selectpicker.js' %}"
        type="text/javascript"></script>

<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="{% static 'accounts/js/plugins/bootstrap-datetimepicker.min.js' %}"
        type="text/javascript"></script>

<!-- Plugins for Presentation Page -->
<!-- Sharrre Library -->
<script src="{% static 'main/js/plugins/jquery.sharrre.js' %}"
        type="text/javascript"></script>

<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="{% static 'accounts/js/now-ui-kit.js' %}" type="text/javascript"></script>

</div>
</body>
</html>

accounts/templates/accounts/sign-up-page.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="gr__demos_creative-tim_com"><head>
<meta charset="utf-8">
<link rel="apple-touch-icon" sizes="76x76" href="{% static "main/img/apple-icon.png" %}">
<link rel="icon" type="image/png" href="{% static "main/img/favicon.png" %}">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<title>Sign Up </title>

<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no" name="viewport">

<!--     Fonts and icons     -->
{#<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet">#}
{#<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">#}

<!-- CSS Files -->
<link href="{% static "accounts/css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static "accounts/css/custom.css" %}" rel="stylesheet">
<link href="{% static "accounts/css/now-ui-kit.css" %}" rel="stylesheet">

</head>

<body class="signup-page" data-gr-c-s-loaded="true">
<nav class="navbar navbar-expand-lg bg-white navbar-absolute navbar-transparent">
	<div class="container">


		<div class="navbar-translate">
			<a class="navbar-brand" href="/" rel="tooltip"
               data-placement="bottom" >
				Home
			</a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
		   		<span class="navbar-toggler-bar bar1"></span>
				<span class="navbar-toggler-bar bar2"></span>
				<span class="navbar-toggler-bar bar3"></span>
		 	</button>
		</div>
    </div>

</nav>

<div class="page-header section-image">
    <div class="page-header-image" style="background-image:url('{% static "accounts/img/bg18.jpg" %}')";></div>
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-md-4 ml-auto mr-auto">
                </div>
                <div class="col-md-4 mr-auto">

                    <div class="card card-signup" style="margin-top:150px">
                        <div class="card-body">
                            <h4 class="card-title text-center">Registrarme</h4>
                            <div class="social text-center">
                                <!-- <button class="btn btn-icon btn-round btn-twitter">
                                    <i class="fa fa-twitter"></i>
                                </button> -->
                                <!-- <button class="btn btn-icon btn-round btn-dribbble">
                                    <i class="fa fa-dribbble"></i>
                                </button> -->
                                <!-- <button class="btn btn-icon btn-round btn-facebook">
                                    <i class="fa fa-facebook"> </i>
                                </button> -->
                                <!-- <h5 class="card-description"> or be classical </h5> -->
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger" role="alert">
                                  <strong>Oh snap!</strong>
                                    {% for error in form.errors %}
                                        {{ form.errors.as_text | escape }}
                                    {% endfor %}
                                </div>
                            {% endif %}

                            <form class="form" method="POST" action="{% url 'accounts:signup' %}">
                                {% csrf_token %}
                                <div class="input-group">
                                  <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="now-ui-icons ui-1_email-85"></i></span>
                                  </div>
                                    {{ form.email }}
                                </div>
                                <div class="input-group">
                                  <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="now-ui-icons ui-1_lock-circle-open"></i>
                                    </span>
                                  </div>
                                    {{ form.password1 }}
                                </div>
                                <div class="input-group">
                                  <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="now-ui-icons ui-1_lock-circle-open"></i>
                                    </span>
                                  </div>
                                    {{ form.password2 }}
                                </div>
                                <input type="hidden" name="next" value="{% url 'accounts:login' %}">
                                <div class="card-footer text-center">
                                    <button type="submit" class="btn btn-primary btn-round btn-lg">Crear Cuenta</button>
                                </div>
                                <div class="card-footer text-center">
                                    <a href='{% url "accounts:login" %}'>Ya tienes una cuenta?</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            <div class="col-md-4 ml-auto mr-auto">
                </div>
            </div>
        </div>
    </div>


    <footer class="footer " style="background-color: black;">


            <div class="container">
                <div class="copyright" style="color: white; float: left;">
                    © 2019, Developed by <a href="" target="_blank">Vittoria Melloni</a>
                    & <a href="" target="_blank"> Jessica Llorente</a>
                </div>
                <div class="copyright" style="color: white; float: right;">
                         Mentored by <a href="" target="_blank">Pablo Ortiz Bochard</a>
                    </div>
            </div>
        
        
        </footer>

</div>





    <!--   Core JS Files   -->
<script src="{% static "main/js/core/jquery.3.2.1.min.js" %}" type="text/javascript"></script>
<script src="{% static "main/js/core/popper.min.js" %}" type="text/javascript"></script>
<script src="{% static "main/js/core/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "accounts/js/plugins/moment.min.js" %}"></script>

<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static "main/js/plugins/bootstrap-switch.js" %}"></script>

<!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
<script src="{% static "accounts/js/plugins/bootstrap-tagsinput.js" %}"></script>

<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="{% static "accounts/js/plugins/bootstrap-selectpicker.js" %}" type="text/javascript"></script>

<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{% static "accounts/js/plugins/jasny-bootstrap.min.js" %}"></script>

<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static "main/js/plugins/nouislider.min.js" %}" type="text/javascript"></script>

<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="{% static "accounts/js/plugins/bootstrap-datetimepicker.min.js" %}" type="text/javascript"></script>

<!-- Plugins for Presentation Page -->
<!-- Sharrre Library -->
<script src="
{% static "main/js/plugins/jquery.sharrre.js" %}" type="text/javascript"></script>

<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="{% static "accounts/js/now-ui-kit.js" %}" type="text/javascript"></script>



<div style="display: none;"></div>
        <div id="shadowMeasureIt"></div>
        <div id="divCoordMeasureIt"></div>
        <div id="divRectangleMeasureIt">
            <div id="divRectangleBGMeasureIt"></div>
            </div>
</body>
</html>